name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - 'main'  # Le pipeline se déclenche sur un push vers la branche principale

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build:
    needs: test  # Ce job démarre après la réussite des tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t aymengharbi/my-app:${{ github.sha }} .
          docker tag aymengharbi/my-app:${{ github.sha }} aymengharbi/my-app:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push aymengharbi/my-app:${{ github.sha }}
          docker push aymengharbi/my-app:latest

